#!/usr/bin/env python3
"""Generate a CISO-oriented resume (docx) from verified employment history."""

import io
import re
import zipfile

from datetime import datetime, timezone

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_LINE_SPACING, WD_TAB_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn, nsmap
from docx.shared import Cm, Pt, RGBColor, Twips, Emu, Inches

NAVY = RGBColor(0x1B, 0x3A, 0x4B)
ACCENT = RGBColor(0x1B, 0x3A, 0x4B)
BODY = RGBColor(0x22, 0x22, 0x22)
MUTED = RGBColor(0x4A, 0x55, 0x5C)
RULE = "1B3A4B"


def _mark_as_ms_word(path):
    """Set Word document properties so Microsoft Word opens it as a native .docx."""
    buf = io.BytesIO()
    with zipfile.ZipFile(path, "r") as zin:
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zout:
            for item in zin.infolist():
                data = zin.read(item.filename)
                if item.filename == "docProps/app.xml":
                    text = data.decode("utf-8")
                    text = re.sub(
                        r"<Application>.*?</Application>",
                        "<Application>Microsoft Office Word</Application>",
                        text,
                    )
                    if "<AppVersion>" not in text:
                        text = text.replace(
                            "</Properties>",
                            "<AppVersion>16.0000</AppVersion></Properties>",
                        )
                    data = text.encode("utf-8")
                elif item.filename == "docProps/core.xml":
                    text = data.decode("utf-8")
                    text = text.replace("generated by python-docx", "")
                    data = text.encode("utf-8")
                zout.writestr(item, data)
    with open(path, "wb") as f:
        f.write(buf.getvalue())


def set_run_font(run, name="Calibri", size=11, bold=False, italic=False, color=BODY):
    run.font.name = name
    run._element.rPr.rFonts.set(qn("w:eastAsia"), name)
    run.font.size = Pt(size)
    run.bold = bold
    run.italic = italic
    run.font.color.rgb = color


def set_paragraph_spacing(p, before=0, after=0, line=1.08, exact=None):
    pf = p.paragraph_format
    pf.space_before = Pt(before)
    pf.space_after = Pt(after)
    if exact is not None:
        pf.line_spacing_rule = WD_LINE_SPACING.EXACTLY
        pf.line_spacing = Pt(exact)
    else:
        pf.line_spacing = line


def add_bottom_border(paragraph, color=RULE, sz="12"):
    pPr = paragraph._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), sz)
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), color)
    pBdr.append(bottom)
    pPr.append(pBdr)


def add_top_border(paragraph, color=RULE, sz="6"):
    pPr = paragraph._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    top = OxmlElement("w:top")
    top.set(qn("w:val"), "single")
    top.set(qn("w:sz"), sz)
    top.set(qn("w:space"), "4")
    top.set(qn("w:color"), color)
    pBdr.append(top)
    pPr.append(pBdr)


def heading(doc, text):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    set_paragraph_spacing(p, before=10, after=4, exact=16)
    add_bottom_border(p, sz="10")
    r = p.add_run(text.upper())
    set_run_font(r, size=11, bold=True, color=NAVY)
    r.font.all_caps = True
    return p


def body_para(doc, text, after=6, before=0, italic=False, size=10.5):
    p = doc.add_paragraph()
    set_paragraph_spacing(p, before=before, after=after, exact=14)
    r = p.add_run(text)
    set_run_font(r, size=size, italic=italic, color=BODY)
    p.paragraph_format.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    return p


def bullet(doc, text, bold_lead=None, size=10.5):
    p = doc.add_paragraph()
    p.style = doc.styles["List Bullet"]
    set_paragraph_spacing(p, before=1, after=2, exact=14)
    p.paragraph_format.left_indent = Cm(0.55)
    p.paragraph_format.first_line_indent = Cm(-0.35)
    if bold_lead:
        r0 = p.add_run(bold_lead)
        set_run_font(r0, size=size, bold=True, color=NAVY)
        r1 = p.add_run(text)
        set_run_font(r1, size=size, color=BODY)
    else:
        r = p.add_run(text)
        set_run_font(r, size=size, color=BODY)
    return p


def subhead(doc, text):
    p = doc.add_paragraph()
    set_paragraph_spacing(p, before=6, after=2, exact=14)
    r = p.add_run(text)
    set_run_font(r, size=10.5, bold=True, italic=True, color=NAVY)
    return p


def job_header(doc, title, dates):
    p = doc.add_paragraph()
    set_paragraph_spacing(p, before=8, after=0, exact=15)
    r1 = p.add_run(title)
    set_run_font(r1, size=11, bold=True, color=NAVY)
    r2 = p.add_run("\t" + dates)
    set_run_font(r2, size=10, bold=True, color=MUTED)
    tab_stops = p.paragraph_format.tab_stops
    tab_stops.add_tab_stop(Cm(17.0), WD_TAB_ALIGNMENT.RIGHT)
    return p


def job_meta(doc, text):
    p = doc.add_paragraph()
    set_paragraph_spacing(p, before=0, after=3, exact=13)
    r = p.add_run(text)
    set_run_font(r, size=10, italic=True, color=MUTED)
    return p


def compact_line(doc, left_bold, right, size=10.5):
    p = doc.add_paragraph()
    set_paragraph_spacing(p, before=1, after=1, exact=14)
    r1 = p.add_run(left_bold)
    set_run_font(r1, size=size, bold=True, color=NAVY)
    r2 = p.add_run(right)
    set_run_font(r2, size=size, color=BODY)
    return p


def set_doc_defaults(doc):
    section = doc.sections[0]
    section.page_width = Cm(21.0)
    section.page_height = Cm(29.7)
    section.left_margin = Cm(1.6)
    section.right_margin = Cm(1.6)
    section.top_margin = Cm(1.3)
    section.bottom_margin = Cm(1.3)

    styles = doc.styles
    normal = styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(10.5)
    normal.font.color.rgb = BODY

    # Tighter bullets
    try:
        lst = styles["List Bullet"]
        lst.font.name = "Calibri"
        lst.font.size = Pt(10.5)
    except KeyError:
        pass


def build():
    doc = Document()
    set_doc_defaults(doc)

    # ----- Header -----
    name = doc.add_paragraph()
    name.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_paragraph_spacing(name, before=0, after=0, exact=22)
    r = name.add_run("SREENIVASA KE")
    set_run_font(r, size=20, bold=True, color=NAVY)

    creds = doc.add_paragraph()
    creds.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_paragraph_spacing(creds, before=1, after=1, exact=14)
    r = creds.add_run("CISM  ·  CISA  ·  PMP  ·  MBA  ·  CSM  ·  CSQA  ·  ITIL")
    set_run_font(r, size=10.5, bold=True, color=MUTED)

    headline = doc.add_paragraph()
    headline.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_paragraph_spacing(headline, before=1, after=1, exact=15)
    r = headline.add_run(
        "Cybersecurity Leader  |  Information Security Governance, Technical Controls & Risk"
    )
    set_run_font(r, size=11, bold=True, color=NAVY)

    contact = doc.add_paragraph()
    contact.alignment = WD_ALIGN_PARAGRAPH.CENTER
    set_paragraph_spacing(contact, before=1, after=2, exact=13)
    add_bottom_border(contact, sz="14")
    r = contact.add_run(
        "Bangalore, India  ·  +91-9886135565  ·  sreenivaske@gmail.com  ·  "
        "English & Mandarin  ·  Open to relocation / travel"
    )
    set_run_font(r, size=9.5, color=MUTED)

    # ----- Profile -----
    heading(doc, "Professional Profile")
    body_para(
        doc,
        "Senior cybersecurity leader with 23+ years in technology, risk and compliance, "
        "including 11+ years dedicated to information security across mission-critical digital "
        "infrastructure, banking and financial services, and healthcare. Combines executive-ready "
        "governance with hands-on ownership of technical controls — secure architecture, "
        "secure SDLC / DevSecOps practices, ISMS, identity and access, encryption, network "
        "and application security, third-party risk, incident response, and BCP/DR.",
        after=4,
    )
    body_para(
        doc,
        "Trusted partner to technology and engineering leadership: embeds security into platform "
        "design and delivery without creating friction, provides independent challenge on residual "
        "risk and go-live readiness, and translates regulatory and customer control requirements "
        "into implementable architecture and operating cadence. Experience building and maturing "
        "security capability during product and platform build phases — governance model, control "
        "design, audit evidence, and engineering enablement — in multi-party, globally distributed "
        "environments. Seeking CISO / Head of Information Security leadership in regulated "
        "payments, banking, fintech, or other critical digital infrastructure.",
        after=2,
    )

    # ----- Core competencies -----
    heading(doc, "Core Competencies")

    compact_line(
        doc,
        "Leadership & governance:  ",
        "Executive / leadership advisory; independent cyber and technology-risk oversight; "
        "security operating model; board-style posture and investment reporting; multi-party stakeholder coordination.",
    )
    compact_line(
        doc,
        "Technical controls:  ",
        "Secure architecture; identity & access / least privilege; encryption controls; "
        "network segmentation; application security (OWASP); cloud (Azure) controls; VAPT; third-party / OSS risk.",
    )
    compact_line(
        doc,
        "Engineering partnership:  ",
        "Secure SDLC / DevSecOps gates; secure coding; product cybersecurity reviews; "
        "embedding controls into platform engineering without blocking delivery.",
    )
    compact_line(
        doc,
        "Operations & resilience:  ",
        "Incident response (8D / QRQC / RCA); ISMS management reviews; BCP and DR test support; "
        "security awareness; milestone cyber-readiness gates for 24/7 operational systems.",
    )
    compact_line(
        doc,
        "Risk, audit & regulation:  ",
        "ISO 27001, NIST CSF / risk, IEC 62443 (SL2/SL3), HIPAA, SOX / GLBA / FFIEC-style gap work; "
        "Singapore CCOP2, HK COP, NCA ECC/OTCC awareness; internal and external audit leadership.",
    )

    # ----- Proof points -----
    heading(doc, "Selected Outcomes")
    bullet(
        doc,
        "Zero major cybersecurity incidents on covered urban / R&D solutions; no cyber blockers at project milestone gates.",
    )
    bullet(
        doc,
        "Mapped mission-critical urban platforms to IEC 62443 SL2 / SL3 and closed security-control gaps for R&D products.",
    )
    bullet(
        doc,
        "100% on-time cybersecurity inputs to customer proposals; bid estimates without material cost overrun into execution.",
    )
    bullet(
        doc,
        "Healthcare programs: zero HIPAA information-security incidents; 100% of infosec incidents closed within agreed time.",
    )
    bullet(
        doc,
        "Banking / FS delivery: coordinated internal and external audits with zero non-compliance findings on covered cycles.",
    )
    bullet(
        doc,
        "Led cybersecurity and infosec teams (6 direct; collaboration scaled to 14) across eight global locations; previously accountable for infosec operating discipline on a 900+ resource banking/FS footprint.",
    )

    # ----- Experience: last 3 employers -----
    heading(doc, "Professional Experience")

    # ALSTOM
    job_header(doc, "ALSTOM  —  Cybersecurity Manager", "Feb 2018 – Present")
    job_meta(
        doc,
        "Rail / urban solutions R&D, Bangalore  ·  24/7 mission-critical operational-technology platforms  ·  "
        "Team leadership, product security, and bid-to-delivery cyber governance",
    )
    body_para(
        doc,
        "Accountable for cybersecurity strategy, technical control design, and delivery assurance for "
        "urban / rail digital platforms. Interface between engineering, bid, and compliance — translating "
        "customer and regulatory security requirements into architecture, controls, residual-risk "
        "decisions, and evidence that leadership can stand behind.",
        after=3,
        italic=True,
        size=10,
    )

    subhead(doc, "Leadership, governance & stakeholder engagement")
    bullet(
        doc,
        "Principal cybersecurity advisor to R&D leadership: monthly reporting on threat-relevant posture, "
        "control gaps, residual risk, and investment / effort priorities; independent challenge on design "
        "and go-live readiness rather than a late compliance stamp.",
        bold_lead="Executive advisory.  ",
    )
    bullet(
        doc,
        "Built and run the cybersecurity function for the center — hiring, budgeting, operating cadence, "
        "and capability development (6-member team; cross-functional collaboration scaled to 14) across "
        "eight global locations. Mentored engineers on secure design ownership.",
        bold_lead="Security operating model.  ",
    )
    bullet(
        doc,
        "Partnered with product engineering and architecture leadership to embed security "
        "into platform design, SDLC, and release gates without creating delivery friction. Acted as "
        "constructive challenger on technology risk, third-party components, and resilience assumptions.",
        bold_lead="Engineering partnership.  ",
    )
    bullet(
        doc,
        "Coordinated security requirements in complex multi-party bid and consortium environments; "
        "provided structured go / no-go on feasibility, control cost, and residual risk so commercial "
        "commitments matched what engineering could securely deliver.",
        bold_lead="Multi-party governance.  ",
    )

    subhead(doc, "Technical controls, architecture & secure engineering")
    bullet(
        doc,
        "Mapped urban / IACS platforms to IEC 62443 SL2 and SL3. Closed gaps across identification and "
        "authentication, use control, system integrity, data confidentiality, restricted data flow, "
        "event response, and resource availability — then tracked remediation into R&D product baselines.",
        bold_lead="Control framework (IEC 62443).  ",
    )
    bullet(
        doc,
        "Directed product cybersecurity reviews covering secure coding, encryption "
        "controls, network security and segmentation expectations, interface / API trust boundaries, "
        "and third-party / open-source software risk before design freeze and milestone gates.",
        bold_lead="Secure architecture & SDLC.  ",
    )
    bullet(
        doc,
        "Aligned lifecycle security controls to ISO 27001 and NIST risk methods, with CENELEC "
        "EN 50126 / 50128 / 50129 interface so cyber controls did not undermine safety integrity on "
        "operational systems.",
        bold_lead="ISMS + safety-adjacent cyber.  ",
    )
    bullet(
        doc,
        "Ran cyber, quality, and safety incident handling using 8D and QRQC (containment, RCA, "
        "corrective and preventive action). Maintained zero major cybersecurity incidents on covered "
        "solutions and kept projects free of cyber blockers at milestone gates.",
        bold_lead="Incident response & resilience.  ",
    )
    bullet(
        doc,
        "Trained engineering teams on secure process and control intent; improved gates and checklists "
        "from live project feedback so controls stayed usable under delivery pressure.",
        bold_lead="Enablement.  ",
    )

    # OPTEAMIX
    job_header(
        doc,
        "OPTEAMIX  —  Program Manager (Process) / HIPAA & Information Security",
        "Oct 2015 – Feb 2018",
    )
    job_meta(
        doc,
        "Healthcare (PHI) and banking / payment-services programs  ·  CISO-office advisory, ISMS, "
        "application security  ·  Top Performer 2017",
    )
    body_para(
        doc,
        "CISO-side consulting and program leadership for healthcare and financial-services clients: "
        "policy, risk assessment, technical control implementation support, incident management, "
        "and audit readiness — including payment-services and banking application estates hosted on Azure.",
        after=3,
        italic=True,
        size=10,
    )

    subhead(doc, "Leadership, governance & program ownership")
    bullet(
        doc,
        "Operated as CISO-office partner: authored and maintained information-security policy, "
        "defined program KPIs, ran incident management, and delivered leadership-ready risk and "
        "compliance reporting across 15+ client engagements.",
        bold_lead="CISO-office support.  ",
    )
    bullet(
        doc,
        "Owned ISMS operating rhythm — control owners, management reviews, evidence packs — and "
        "worked with external audit vendors on ISO 27001 and HIPAA readiness through remediation close-out.",
        bold_lead="ISMS & audit leadership.  ",
    )
    bullet(
        doc,
        "Set security goals and training cadence for delivery teams handling PHI / PII and financial data; "
        "held programs to zero HIPAA information-security incidents and to SLA on infosec incident closure.",
        bold_lead="Accountability.  ",
    )

    subhead(doc, "Technical controls & security engineering")
    bullet(
        doc,
        "Led risk assessments and VAPT support; aligned application programs to OWASP secure-coding "
        "practices, SSO, encryption in transit and at rest, and Azure hosting / identity controls.",
        bold_lead="Application, identity & cloud.  ",
    )
    bullet(
        doc,
        "Built and maintained ISMS policies, BCP elements, and vulnerability / threat classification "
        "so residual risk, patch priority, and exception handling were explicit and repeatable.",
        bold_lead="Risk, BCP & threat classification.  ",
    )
    bullet(
        doc,
        "Embedded secure development practices into application programs (requirements, code, hosting) "
        "for healthcare and financial / payment-services workloads — precursor DevSecOps discipline "
        "across mixed on-prem and cloud estates.",
        bold_lead="Secure SDLC.  ",
    )

    # HCL
    job_header(
        doc,
        "HCL TECHNOLOGIES  —  Manager, Process & Information Security",
        "Nov 2005 – Oct 2015",
    )
    job_meta(
        doc,
        "Banking and financial-services delivery  ·  900+ resource footprint (development, production "
        "support, testing)  ·  Top Talent Transformer — 3 consecutive years",
    )
    body_para(
        doc,
        "Led process and information security for large regulated banking / FS accounts. Combined "
        "control operation (access, awareness, backup, physical and network hygiene) with ISMS "
        "governance, vendor risk, BCP/DR test support, and audit interface for global financial institutions.",
        after=3,
        italic=True,
        size=10,
    )

    subhead(doc, "Leadership, governance & regulatory engagement")
    bullet(
        doc,
        "Led the process and infosec team for a 900+ person banking / FS delivery estate; accountable "
        "for control effectiveness, audit outcomes, CSAT, time-to-market, and operating discipline "
        "across development, production support, and testing.",
        bold_lead="Function leadership.  ",
    )
    bullet(
        doc,
        "Primary interface with internal and external auditors on major global bank programs; "
        "coordinated evidence, walkthroughs, and remediation. Zero non-compliance findings on "
        "coordinated audit cycles.",
        bold_lead="Audit & examiner interface.  ",
    )
    bullet(
        doc,
        "Ran ISMS management reviews; sponsored ISO/IEC 27001 implementation and recertification "
        "for banking accounts. Translated SOX, GLBA, and FFIEC-style expectations into gap analysis, "
        "control owners, and closure plans.",
        bold_lead="ISMS & FS regulatory mapping.  ",
    )
    bullet(
        doc,
        "Delivered security awareness tailored to financial-sector obligations; drove tool adoption "
        "and process change so controls were lived in development, production support, and testing.",
        bold_lead="Culture & enablement.  ",
    )

    subhead(doc, "Technical controls, operations & resilience")
    bullet(
        doc,
        "Operated identity and access controls: periodic access reviews, least-privilege enforcement, "
        "and joiner–mover–leaver hygiene across large delivery footprints.",
        bold_lead="Identity & access.  ",
    )
    bullet(
        doc,
        "Ran phishing simulations, backup restoration validation, wireless security audits, clean-desk "
        "and anti-piggybacking checks — detective and preventive controls with documented exceptions "
        "and follow-up.",
        bold_lead="Preventive & detective controls.  ",
    )
    bullet(
        doc,
        "Performed third-party / vendor risk reviews for suppliers touching regulated environments; "
        "supported BCP and disaster-recovery tests so recovery assumptions were evidenced, not assumed.",
        bold_lead="Third-party risk & BCP/DR.  ",
    )
    bullet(
        doc,
        "Established NIST- and CIS-oriented policy and control baselines for the period, giving "
        "engineering and operations a practical control catalogue rather than generic policy text.",
        bold_lead="Control baselines.  ",
    )

    # ----- Earlier career -----
    heading(doc, "Earlier Career — Product R&D, China (quality + secure SDLC foundations)")
    body_para(
        doc,
        "4.5 years in China (Mandarin working level). Built secure-development and quality gates in "
        "embedded product R&D — relevant to embedding security into engineering culture during platform build.",
        after=3,
        italic=True,
        size=10,
    )
    compact_line(
        doc,
        "Konka — Lead, Quality & Infosec Assurance (China) | Dec 2003 – Nov 2005.  ",
        "Designed a Secure Development Lifecycle (gap analysis, security/quality gates, roles, metrics) "
        "across 30–45 embedded projects a year; reworked requirements, code review, and SCM to put "
        "security checks early; governed high-risk HW/SW programs; took IT R&D through CMMI L3. "
        "Results: 0 residual defects/KLOC after system test; ~95% review efficiency; ~95% schedule adherence with security in the path.",
        size=10,
    )
    compact_line(
        doc,
        "Zhengeda Software — Process Coordinator (China) | Dec 2001 – Dec 2003.  ",
        "Quality planning with software teams; project-managed CMMI L3 implementation covering 12 R&D projects / ~85 resources.",
        size=10,
    )
    compact_line(
        doc,
        "Huawei — Software Engineer → SEPG / SQA (China) | Dec 2000 – Dec 2001.  ",
        "Home Location Register (HLR) product work, then PPQA / SQA on four major telecom projects — "
        "early exposure to carrier-grade, high-availability infrastructure.",
        size=10,
    )
    compact_line(
        doc,
        "Ionidea — Software Engineer | Jun 2000 – Dec 2000.  ",
        "Development and support on intranet–internet application suite.",
        size=10,
    )

    # ----- Certs / education / frameworks -----
    heading(doc, "Certifications")
    compact_line(doc, "CISM  ", "— ISACA, Dec 2021  ·  #242577298")
    compact_line(doc, "CISA  ", "— ISACA, Aug 2026")
    compact_line(doc, "PMP  ", "— PMI, 2009  ·  #1230636")
    compact_line(doc, "CSQA  ", "— QAI, 2008     ·     CSM — Scrum Alliance, 2015     ·     ITIL Foundation, 2011")

    heading(doc, "Education")
    compact_line(doc, "MBA, Quality Management  ", "— SMU, Bangalore, 2012")
    compact_line(doc, "B.Sc., Mathematics  ", "— Bangalore University, 1997")

    heading(doc, "Standards, Regulatory & Control Frameworks")
    body_para(
        doc,
        "Day-to-day: IEC 62443 (SL2/SL3), ISO 27001 / ISMS, NIST CSF and risk methods, HIPAA, "
        "CENELEC EN 50126/28/29 (safety-adjacent cyber), CMMI, ITIL, OWASP, CIS-oriented baselines, "
        "SOX / GLBA / FFIEC-style mapping.",
        after=3,
        size=10,
    )
    body_para(
        doc,
        "APAC and CII-relevant codes worked with or tracked: Singapore CCOP2; Hong Kong COP; "
        "Australian AS 7770 and Privacy Act / cyber-strategy awareness. Middle East bid mapping: "
        "Saudi NCA ECC / OTCC; UAE Information Assurance; Egypt Cybersecurity Law. Comfortable "
        "extending the same control-mapping method to additional payments and FS regimes "
        "(PCI-DSS, technology-risk guidelines, cross-border data protection) as required.",
        after=3,
        size=10,
    )

    heading(doc, "Languages")
    body_para(
        doc,
        "English, Mandarin (working), Kannada, Telugu, Tamil, Hindi.",
        after=2,
        size=10.5,
    )

    note = doc.add_paragraph()
    set_paragraph_spacing(note, before=8, after=0, exact=13)
    add_top_border(note, sz="8")
    r = note.add_run(
        "References and a detailed control / project list available on request. "
        "Happy to walk through a live architecture-risk, ISMS, or bid-to-control case in interview."
    )
    set_run_font(r, size=9, italic=True, color=MUTED)

    cp = doc.core_properties
    cp.author = "Sreenivasa KE"
    cp.last_modified_by = "Sreenivasa KE"
    cp.title = "Sreenivasa KE — Resume"
    cp.subject = "Cybersecurity / Information Security Leader"
    cp.category = "Resume"
    cp.keywords = "CISO; Information Security; Cybersecurity; ISO 27001; NIST; IEC 62443"
    cp.comments = ""
    now = datetime.now(timezone.utc)
    cp.created = now
    cp.modified = now

    import os
    import shutil

    out_paths = [
        "/workspace/Sreenivasa_KE_Resume.docx",
        "/workspace/Sreenivasa_KE_Resume_CISO_Information_Security.docx",
    ]
    doc.save(out_paths[0])
    shutil.copy2(out_paths[0], out_paths[1])
    artifacts = "/opt/cursor/artifacts"
    if os.path.isdir(artifacts):
        art = os.path.join(artifacts, "Sreenivasa_KE_Resume.docx")
        shutil.copy2(out_paths[0], art)
        out_paths.append(art)
    for path in out_paths:
        _mark_as_ms_word(path)
        print("Wrote", path)


if __name__ == "__main__":
    build()
